project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1 - SF and EDA
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1_SFEDA.html
          - text: Hands-on Exercise 1 - Choropleth Mapping
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1_Choropleth.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-Class_ex/In-Class_Ex1/In-class_Ex1.html
    right:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

